### ISSUE TITLE
Rename the repository to Mighty Lemon

### ISSUE THREAD

**Issue by jezdez** [brosner/oebfare#1]
Since a new name was found we should just use it and move on to implement features.

**Comment by brosner** [comment]
Hmm, it was supposed to be Mighty Lemon, but I almost like this better :-D (I don't care either way)

**Comment by jezdez** [comment]
LOL, going to change it from Mighty Melon to Mighty Lemon.

**Comment by ericflo** [comment]
This is cool.

**Comment by leah** [comment]
Okay, I've moved the repo to http://github.com/mightylemon/mightylemon so I'm closing this ticket :P

**Comment by leah** [comment]
closing
